# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
